// <auto-generated />
namespace DbAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kluczzwrotnydlaskladnikaprzepisu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kluczzwrotnydlaskladnikaprzepisu));
        
        string IMigrationMetadata.Id
        {
            get { return "201509162254422_klucz zwrotny dla skladnika przepisu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
