// <auto-generated />
namespace DbAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodanomozliwoscdostepudodanychouzytkownikuodstronylist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodanomozliwoscdostepudodanychouzytkownikuodstronylist));
        
        string IMigrationMetadata.Id
        {
            get { return "201509060016261_Dodano mozliwosc dostepu do danych o uzytkowniku od strony list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
